name: Build

on: 
  workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04,windows-2022, windows-2019,macOS-12, macOS-11]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - name: Set up QEMU 
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD_FRONTEND: "build; args: --no-isolation"
          CIBW_BEFORE_BUILD: pip install Cython==3.0.6 chardet==5.2.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl